//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.225
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 端口侦听控制系统.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string grp_listening_comunication_config_port_name {
            get {
                return ((string)(this["grp_listening_comunication_config_port_name"]));
            }
            set {
                this["grp_listening_comunication_config_port_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int grp_listening_comunication_config_baud_rate {
            get {
                return ((int)(this["grp_listening_comunication_config_baud_rate"]));
            }
            set {
                this["grp_listening_comunication_config_baud_rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int grp_listening_comunication_config_databit {
            get {
                return ((int)(this["grp_listening_comunication_config_databit"]));
            }
            set {
                this["grp_listening_comunication_config_databit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string grp_listening_comunication_config_parity {
            get {
                return ((string)(this["grp_listening_comunication_config_parity"]));
            }
            set {
                this["grp_listening_comunication_config_parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public string grp_listening_comunication_config_stopbit {
            get {
                return ((string)(this["grp_listening_comunication_config_stopbit"]));
            }
            set {
                this["grp_listening_comunication_config_stopbit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string grp_output_1_port_comunication_config_port_name {
            get {
                return ((string)(this["grp_output_1_port_comunication_config_port_name"]));
            }
            set {
                this["grp_output_1_port_comunication_config_port_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int grp_output_1_port_comunication_config_baud_rate {
            get {
                return ((int)(this["grp_output_1_port_comunication_config_baud_rate"]));
            }
            set {
                this["grp_output_1_port_comunication_config_baud_rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int grp_output_1_port_comunication_config_databit {
            get {
                return ((int)(this["grp_output_1_port_comunication_config_databit"]));
            }
            set {
                this["grp_output_1_port_comunication_config_databit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string grp_output_1_port_comunication_config_parity {
            get {
                return ((string)(this["grp_output_1_port_comunication_config_parity"]));
            }
            set {
                this["grp_output_1_port_comunication_config_parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public string grp_output_1_port_comunication_config_stopbit {
            get {
                return ((string)(this["grp_output_1_port_comunication_config_stopbit"]));
            }
            set {
                this["grp_output_1_port_comunication_config_stopbit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string grp_output_2_port_comunication_config_port_name {
            get {
                return ((string)(this["grp_output_2_port_comunication_config_port_name"]));
            }
            set {
                this["grp_output_2_port_comunication_config_port_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int grp_output_2_port_comunication_config_baud_rate {
            get {
                return ((int)(this["grp_output_2_port_comunication_config_baud_rate"]));
            }
            set {
                this["grp_output_2_port_comunication_config_baud_rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int grp_output_2_port_comunication_config_databit {
            get {
                return ((int)(this["grp_output_2_port_comunication_config_databit"]));
            }
            set {
                this["grp_output_2_port_comunication_config_databit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string grp_output_2_port_comunication_config_parity {
            get {
                return ((string)(this["grp_output_2_port_comunication_config_parity"]));
            }
            set {
                this["grp_output_2_port_comunication_config_parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public string grp_output_2_port_comunication_config_stopbit {
            get {
                return ((string)(this["grp_output_2_port_comunication_config_stopbit"]));
            }
            set {
                this["grp_output_2_port_comunication_config_stopbit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string grp_output_3_port_comunication_config_port_name {
            get {
                return ((string)(this["grp_output_3_port_comunication_config_port_name"]));
            }
            set {
                this["grp_output_3_port_comunication_config_port_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int grp_output_3_port_comunication_config_baud_rate {
            get {
                return ((int)(this["grp_output_3_port_comunication_config_baud_rate"]));
            }
            set {
                this["grp_output_3_port_comunication_config_baud_rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int grp_output_3_port_comunication_config_databit {
            get {
                return ((int)(this["grp_output_3_port_comunication_config_databit"]));
            }
            set {
                this["grp_output_3_port_comunication_config_databit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string grp_output_3_port_comunication_config_parity {
            get {
                return ((string)(this["grp_output_3_port_comunication_config_parity"]));
            }
            set {
                this["grp_output_3_port_comunication_config_parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public string grp_output_3_port_comunication_config_stopbit {
            get {
                return ((string)(this["grp_output_3_port_comunication_config_stopbit"]));
            }
            set {
                this["grp_output_3_port_comunication_config_stopbit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string grp_output_4_port_comunication_config_port_name {
            get {
                return ((string)(this["grp_output_4_port_comunication_config_port_name"]));
            }
            set {
                this["grp_output_4_port_comunication_config_port_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9600")]
        public int grp_output_4_port_comunication_config_baud_rate {
            get {
                return ((int)(this["grp_output_4_port_comunication_config_baud_rate"]));
            }
            set {
                this["grp_output_4_port_comunication_config_baud_rate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int grp_output_4_port_comunication_config_databit {
            get {
                return ((int)(this["grp_output_4_port_comunication_config_databit"]));
            }
            set {
                this["grp_output_4_port_comunication_config_databit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public string grp_output_4_port_comunication_config_parity {
            get {
                return ((string)(this["grp_output_4_port_comunication_config_parity"]));
            }
            set {
                this["grp_output_4_port_comunication_config_parity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("One")]
        public string grp_output_4_port_comunication_config_stopbit {
            get {
                return ((string)(this["grp_output_4_port_comunication_config_stopbit"]));
            }
            set {
                this["grp_output_4_port_comunication_config_stopbit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_1_control_config_shoot_delay {
            get {
                return ((int)(this["grp_output_1_control_config_shoot_delay"]));
            }
            set {
                this["grp_output_1_control_config_shoot_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_1_control_config_series_shoot_timer {
            get {
                return ((int)(this["grp_output_1_control_config_series_shoot_timer"]));
            }
            set {
                this["grp_output_1_control_config_series_shoot_timer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_1_control_config_shoot_neglect {
            get {
                return ((string)(this["grp_output_1_control_config_shoot_neglect"]));
            }
            set {
                this["grp_output_1_control_config_shoot_neglect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_2_control_config_shoot_delay {
            get {
                return ((int)(this["grp_output_2_control_config_shoot_delay"]));
            }
            set {
                this["grp_output_2_control_config_shoot_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_2_control_config_series_shoot_timer {
            get {
                return ((int)(this["grp_output_2_control_config_series_shoot_timer"]));
            }
            set {
                this["grp_output_2_control_config_series_shoot_timer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_2_control_config_shoot_neglect {
            get {
                return ((string)(this["grp_output_2_control_config_shoot_neglect"]));
            }
            set {
                this["grp_output_2_control_config_shoot_neglect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_3_control_config_shoot_delay {
            get {
                return ((int)(this["grp_output_3_control_config_shoot_delay"]));
            }
            set {
                this["grp_output_3_control_config_shoot_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_3_control_config_series_shoot_timer {
            get {
                return ((int)(this["grp_output_3_control_config_series_shoot_timer"]));
            }
            set {
                this["grp_output_3_control_config_series_shoot_timer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_3_control_config_shoot_neglect {
            get {
                return ((string)(this["grp_output_3_control_config_shoot_neglect"]));
            }
            set {
                this["grp_output_3_control_config_shoot_neglect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_4_control_config_shoot_delay {
            get {
                return ((int)(this["grp_output_4_control_config_shoot_delay"]));
            }
            set {
                this["grp_output_4_control_config_shoot_delay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_4_control_config_series_shoot_timer {
            get {
                return ((int)(this["grp_output_4_control_config_series_shoot_timer"]));
            }
            set {
                this["grp_output_4_control_config_series_shoot_timer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_4_control_config_shoot_neglect {
            get {
                return ((string)(this["grp_output_4_control_config_shoot_neglect"]));
            }
            set {
                this["grp_output_4_control_config_shoot_neglect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_1_type {
            get {
                return ((int)(this["grp_output_1_type"]));
            }
            set {
                this["grp_output_1_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_2_type {
            get {
                return ((int)(this["grp_output_2_type"]));
            }
            set {
                this["grp_output_2_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_3_type {
            get {
                return ((int)(this["grp_output_3_type"]));
            }
            set {
                this["grp_output_3_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_4_type {
            get {
                return ((int)(this["grp_output_4_type"]));
            }
            set {
                this["grp_output_4_type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_1_port_write_data {
            get {
                return ((string)(this["grp_output_1_port_write_data"]));
            }
            set {
                this["grp_output_1_port_write_data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_2_port_write_data {
            get {
                return ((string)(this["grp_output_2_port_write_data"]));
            }
            set {
                this["grp_output_2_port_write_data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_3_port_write_data {
            get {
                return ((string)(this["grp_output_3_port_write_data"]));
            }
            set {
                this["grp_output_3_port_write_data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_4_port_write_data {
            get {
                return ((string)(this["grp_output_4_port_write_data"]));
            }
            set {
                this["grp_output_4_port_write_data"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autorun_listening {
            get {
                return ((bool)(this["autorun_listening"]));
            }
            set {
                this["autorun_listening"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autorun_output_1 {
            get {
                return ((bool)(this["autorun_output_1"]));
            }
            set {
                this["autorun_output_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autorun_output_2 {
            get {
                return ((bool)(this["autorun_output_2"]));
            }
            set {
                this["autorun_output_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autorun_output_3 {
            get {
                return ((bool)(this["autorun_output_3"]));
            }
            set {
                this["autorun_output_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool autorun_output_4 {
            get {
                return ((bool)(this["autorun_output_4"]));
            }
            set {
                this["autorun_output_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_1_message_data_1 {
            get {
                return ((string)(this["grp_output_1_message_data_1"]));
            }
            set {
                this["grp_output_1_message_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_1_message_data_2 {
            get {
                return ((string)(this["grp_output_1_message_data_2"]));
            }
            set {
                this["grp_output_1_message_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_2_message_data_1 {
            get {
                return ((string)(this["grp_output_2_message_data_1"]));
            }
            set {
                this["grp_output_2_message_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_2_message_data_2 {
            get {
                return ((string)(this["grp_output_2_message_data_2"]));
            }
            set {
                this["grp_output_2_message_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_3_message_data_1 {
            get {
                return ((string)(this["grp_output_3_message_data_1"]));
            }
            set {
                this["grp_output_3_message_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_3_message_data_2 {
            get {
                return ((string)(this["grp_output_3_message_data_2"]));
            }
            set {
                this["grp_output_3_message_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_4_message_data_1 {
            get {
                return ((string)(this["grp_output_4_message_data_1"]));
            }
            set {
                this["grp_output_4_message_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_4_message_data_2 {
            get {
                return ((string)(this["grp_output_4_message_data_2"]));
            }
            set {
                this["grp_output_4_message_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_1_window_data_1 {
            get {
                return ((string)(this["grp_output_1_window_data_1"]));
            }
            set {
                this["grp_output_1_window_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_1_window_data_2 {
            get {
                return ((string)(this["grp_output_1_window_data_2"]));
            }
            set {
                this["grp_output_1_window_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_2_window_data_1 {
            get {
                return ((string)(this["grp_output_2_window_data_1"]));
            }
            set {
                this["grp_output_2_window_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_2_window_data_2 {
            get {
                return ((string)(this["grp_output_2_window_data_2"]));
            }
            set {
                this["grp_output_2_window_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_3_window_data_1 {
            get {
                return ((string)(this["grp_output_3_window_data_1"]));
            }
            set {
                this["grp_output_3_window_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_3_window_data_2 {
            get {
                return ((string)(this["grp_output_3_window_data_2"]));
            }
            set {
                this["grp_output_3_window_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_4_window_data_1 {
            get {
                return ((string)(this["grp_output_4_window_data_1"]));
            }
            set {
                this["grp_output_4_window_data_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string grp_output_4_window_data_2 {
            get {
                return ((string)(this["grp_output_4_window_data_2"]));
            }
            set {
                this["grp_output_4_window_data_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_1_control_config_additional_number {
            get {
                return ((int)(this["grp_output_1_control_config_additional_number"]));
            }
            set {
                this["grp_output_1_control_config_additional_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_1_control_config_additional_amount {
            get {
                return ((int)(this["grp_output_1_control_config_additional_amount"]));
            }
            set {
                this["grp_output_1_control_config_additional_amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_1_control_config_additional_interval {
            get {
                return ((int)(this["grp_output_1_control_config_additional_interval"]));
            }
            set {
                this["grp_output_1_control_config_additional_interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_2_control_config_additional_number {
            get {
                return ((int)(this["grp_output_2_control_config_additional_number"]));
            }
            set {
                this["grp_output_2_control_config_additional_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_2_control_config_additional_amount {
            get {
                return ((int)(this["grp_output_2_control_config_additional_amount"]));
            }
            set {
                this["grp_output_2_control_config_additional_amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_2_control_config_additional_interval {
            get {
                return ((int)(this["grp_output_2_control_config_additional_interval"]));
            }
            set {
                this["grp_output_2_control_config_additional_interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_3_control_config_additional_number {
            get {
                return ((int)(this["grp_output_3_control_config_additional_number"]));
            }
            set {
                this["grp_output_3_control_config_additional_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_3_control_config_additional_amount {
            get {
                return ((int)(this["grp_output_3_control_config_additional_amount"]));
            }
            set {
                this["grp_output_3_control_config_additional_amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_3_control_config_additional_interval {
            get {
                return ((int)(this["grp_output_3_control_config_additional_interval"]));
            }
            set {
                this["grp_output_3_control_config_additional_interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_4_control_config_additional_number {
            get {
                return ((int)(this["grp_output_4_control_config_additional_number"]));
            }
            set {
                this["grp_output_4_control_config_additional_number"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int grp_output_4_control_config_additional_amount {
            get {
                return ((int)(this["grp_output_4_control_config_additional_amount"]));
            }
            set {
                this["grp_output_4_control_config_additional_amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int grp_output_4_control_config_additional_interval {
            get {
                return ((int)(this["grp_output_4_control_config_additional_interval"]));
            }
            set {
                this["grp_output_4_control_config_additional_interval"] = value;
            }
        }
    }
}
